# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_05/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SudokuWindow(object):
    def setupUi(self, SudokuWindow):
        SudokuWindow.setObjectName("SudokuWindow")
        SudokuWindow.resize(600, 650)
        self.centralwidget = QtWidgets.QWidget(SudokuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addWidget(self.gridWidget)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.buttonsLayout.addWidget(self.clearButton)
        self.validateButton = QtWidgets.QPushButton(self.centralwidget)
        self.validateButton.setObjectName("validateButton")
        self.buttonsLayout.addWidget(self.validateButton)
        self.verticalLayout.addLayout(self.buttonsLayout)
        SudokuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SudokuWindow)
        QtCore.QMetaObject.connectSlotsByName(SudokuWindow)

    def retranslateUi(self, SudokuWindow):
        _translate = QtCore.QCoreApplication.translate
        SudokuWindow.setWindowTitle(_translate("SudokuWindow", "Sudoku"))
        self.clearButton.setText(_translate("SudokuWindow", "Clear"))
        self.validateButton.setText(_translate("SudokuWindow", "Validate"))
