# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_16/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimetableForm(object):
    def setupUi(self, TimetableForm):
        TimetableForm.setObjectName("TimetableForm")
        TimetableForm.resize(620, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimetableForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(TimetableForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.labelInput = QtWidgets.QLabel(TimetableForm)
        self.labelInput.setObjectName("labelInput")
        self.verticalLayout.addWidget(self.labelInput)
        self.tableInput = QtWidgets.QTableWidget(TimetableForm)
        self.tableInput.setObjectName("tableInput")
        self.tableInput.setColumnCount(0)
        self.tableInput.setRowCount(0)
        self.verticalLayout.addWidget(self.tableInput)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonExample = QtWidgets.QPushButton(TimetableForm)
        self.buttonExample.setObjectName("buttonExample")
        self.buttonLayout.addWidget(self.buttonExample)
        self.buttonSolve = QtWidgets.QPushButton(TimetableForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.buttonLayout.addWidget(self.buttonSolve)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.labelSchedule = QtWidgets.QLabel(TimetableForm)
        self.labelSchedule.setObjectName("labelSchedule")
        self.verticalLayout.addWidget(self.labelSchedule)
        self.tableSchedule = QtWidgets.QTableWidget(TimetableForm)
        self.tableSchedule.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSchedule.setObjectName("tableSchedule")
        self.tableSchedule.setColumnCount(0)
        self.tableSchedule.setRowCount(0)
        self.verticalLayout.addWidget(self.tableSchedule)
        self.labelStatus = QtWidgets.QLabel(TimetableForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(TimetableForm)
        QtCore.QMetaObject.connectSlotsByName(TimetableForm)

    def retranslateUi(self, TimetableForm):
        _translate = QtCore.QCoreApplication.translate
        TimetableForm.setWindowTitle(_translate("TimetableForm", "Raspored casova"))
        self.labelTitle.setText(_translate("TimetableForm", "Raspored casova ogranicenjima"))
        self.labelInput.setText(_translate("TimetableForm", "Ulazni casovi"))
        self.buttonExample.setText(_translate("TimetableForm", "Ucitaj primer"))
        self.buttonSolve.setText(_translate("TimetableForm", "Napravi raspored"))
        self.labelSchedule.setText(_translate("TimetableForm", "Raspored"))
        self.labelStatus.setText(_translate("TimetableForm", "Spremno."))
