# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.8/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setObjectName("label_title")
        self.mainLayout.addWidget(self.label_title)
        self.topButtonLayout = QtWidgets.QHBoxLayout()
        self.topButtonLayout.setObjectName("topButtonLayout")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setObjectName("btn_one")
        self.topButtonLayout.addWidget(self.btn_one)
        self.btn_two = QtWidgets.QPushButton(self.centralwidget)
        self.btn_two.setObjectName("btn_two")
        self.topButtonLayout.addWidget(self.btn_two)
        self.btn_three = QtWidgets.QPushButton(self.centralwidget)
        self.btn_three.setObjectName("btn_three")
        self.topButtonLayout.addWidget(self.btn_three)
        self.mainLayout.addLayout(self.topButtonLayout)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.mainLayout.addWidget(self.label_status)
        self.bottomButtonLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonLayout.setObjectName("bottomButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtonLayout.addItem(spacerItem)
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setObjectName("btn_ok")
        self.bottomButtonLayout.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.bottomButtonLayout.addWidget(self.btn_cancel)
        self.mainLayout.addLayout(self.bottomButtonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Layout Buttons Example"))
        self.label_title.setText(_translate("MainWindow", "Horizontal Layout"))
        self.btn_one.setText(_translate("MainWindow", "Button One"))
        self.btn_two.setText(_translate("MainWindow", "Button Two"))
        self.btn_three.setText(_translate("MainWindow", "Button Three"))
        self.label_status.setText(_translate("MainWindow", "Status: Ready"))
        self.btn_ok.setText(_translate("MainWindow", "OK"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel"))
