# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.3/temperature_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemperatureConverter(object):
    def setupUi(self, TemperatureConverter):
        TemperatureConverter.setObjectName("TemperatureConverter")
        TemperatureConverter.resize(350, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(TemperatureConverter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(TemperatureConverter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.lineEditCelsius = QtWidgets.QLineEdit(TemperatureConverter)
        self.lineEditCelsius.setObjectName("lineEditCelsius")
        self.verticalLayout.addWidget(self.lineEditCelsius)
        self.buttonConvert = QtWidgets.QPushButton(TemperatureConverter)
        self.buttonConvert.setObjectName("buttonConvert")
        self.verticalLayout.addWidget(self.buttonConvert)
        self.labelResult = QtWidgets.QLabel(TemperatureConverter)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(TemperatureConverter)
        QtCore.QMetaObject.connectSlotsByName(TemperatureConverter)

    def retranslateUi(self, TemperatureConverter):
        _translate = QtCore.QCoreApplication.translate
        TemperatureConverter.setWindowTitle(_translate("TemperatureConverter", "Konvertor temperature"))
        self.labelTitle.setText(_translate("TemperatureConverter", "Konvertor °C → °F"))
        self.labelTitle.setStyleSheet(_translate("TemperatureConverter", "font-size: 18px;"))
        self.lineEditCelsius.setPlaceholderText(_translate("TemperatureConverter", "Unesi temperaturu u °C"))
        self.buttonConvert.setText(_translate("TemperatureConverter", "Konvertuj"))
        self.labelResult.setStyleSheet(_translate("TemperatureConverter", "font-size: 16px;"))
