# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.5/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(50, 20, 300, 30))
        self.label_info.setObjectName("label_info")
        self.checkBox_A = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_A.setGeometry(QtCore.QRect(50, 70, 150, 20))
        self.checkBox_A.setObjectName("checkBox_A")
        self.checkBox_B = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_B.setGeometry(QtCore.QRect(50, 100, 150, 20))
        self.checkBox_B.setObjectName("checkBox_B")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Checkbox Signals"))
        self.label_info.setText(_translate("MainWindow", "Toggle a checkbox"))
        self.checkBox_A.setText(_translate("MainWindow", "Option A"))
        self.checkBox_B.setText(_translate("MainWindow", "Option B"))
