# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_11/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SudokuForm(object):
    def setupUi(self, SudokuForm):
        SudokuForm.setObjectName("SudokuForm")
        SudokuForm.resize(430, 470)
        self.verticalLayout = QtWidgets.QVBoxLayout(SudokuForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(SudokuForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.tableGrid = QtWidgets.QTableWidget(SudokuForm)
        self.tableGrid.setObjectName("tableGrid")
        self.tableGrid.setColumnCount(0)
        self.tableGrid.setRowCount(0)
        self.verticalLayout.addWidget(self.tableGrid)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonExample = QtWidgets.QPushButton(SudokuForm)
        self.buttonExample.setObjectName("buttonExample")
        self.buttonLayout.addWidget(self.buttonExample)
        self.buttonSolve = QtWidgets.QPushButton(SudokuForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.buttonLayout.addWidget(self.buttonSolve)
        self.buttonClear = QtWidgets.QPushButton(SudokuForm)
        self.buttonClear.setObjectName("buttonClear")
        self.buttonLayout.addWidget(self.buttonClear)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.labelStatus = QtWidgets.QLabel(SudokuForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(SudokuForm)
        QtCore.QMetaObject.connectSlotsByName(SudokuForm)

    def retranslateUi(self, SudokuForm):
        _translate = QtCore.QCoreApplication.translate
        SudokuForm.setWindowTitle(_translate("SudokuForm", "Sudoku resavac"))
        self.labelTitle.setText(_translate("SudokuForm", "Sudoku resavac ogranicenjima"))
        self.buttonExample.setText(_translate("SudokuForm", "Ucitaj primer"))
        self.buttonSolve.setText(_translate("SudokuForm", "Resi"))
        self.buttonClear.setText(_translate("SudokuForm", "Ocisti"))
        self.labelStatus.setText(_translate("SudokuForm", "Spremno."))
