# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_02/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesWindow(object):
    def setupUi(self, NotesWindow):
        NotesWindow.setObjectName("NotesWindow")
        NotesWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(NotesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.notesList = QtWidgets.QListWidget(self.centralwidget)
        self.notesList.setObjectName("notesList")
        self.leftLayout.addWidget(self.notesList)
        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        self.newButton.setObjectName("newButton")
        self.leftLayout.addWidget(self.newButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.leftLayout.addWidget(self.saveButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.leftLayout.addWidget(self.deleteButton)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.editor = QtWidgets.QTextEdit(self.centralwidget)
        self.editor.setObjectName("editor")
        self.horizontalLayout.addWidget(self.editor)
        NotesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NotesWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesWindow)

    def retranslateUi(self, NotesWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesWindow.setWindowTitle(_translate("NotesWindow", "In-Memory Notes App"))
        self.newButton.setText(_translate("NotesWindow", "New"))
        self.saveButton.setText(_translate("NotesWindow", "Save"))
        self.deleteButton.setText(_translate("NotesWindow", "Delete"))
