# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_07/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoinChangeForm(object):
    def setupUi(self, CoinChangeForm):
        CoinChangeForm.setObjectName("CoinChangeForm")
        CoinChangeForm.resize(520, 330)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoinChangeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(CoinChangeForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.labelAmount = QtWidgets.QLabel(CoinChangeForm)
        self.labelAmount.setObjectName("labelAmount")
        self.inputLayout.addWidget(self.labelAmount)
        self.spinAmount = QtWidgets.QSpinBox(CoinChangeForm)
        self.spinAmount.setMinimum(0)
        self.spinAmount.setMaximum(500)
        self.spinAmount.setProperty("value", 50)
        self.spinAmount.setObjectName("spinAmount")
        self.inputLayout.addWidget(self.spinAmount)
        self.buttonSolve = QtWidgets.QPushButton(CoinChangeForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.inputLayout.addWidget(self.buttonSolve)
        self.verticalLayout.addLayout(self.inputLayout)
        self.tableResults = QtWidgets.QTableWidget(CoinChangeForm)
        self.tableResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResults.setObjectName("tableResults")
        self.tableResults.setColumnCount(0)
        self.tableResults.setRowCount(0)
        self.verticalLayout.addWidget(self.tableResults)
        self.labelStatus = QtWidgets.QLabel(CoinChangeForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(CoinChangeForm)
        QtCore.QMetaObject.connectSlotsByName(CoinChangeForm)

    def retranslateUi(self, CoinChangeForm):
        _translate = QtCore.QCoreApplication.translate
        CoinChangeForm.setWindowTitle(_translate("CoinChangeForm", "Razmena novca"))
        self.labelTitle.setText(_translate("CoinChangeForm", "Razmena novca ogranicenjima"))
        self.labelAmount.setText(_translate("CoinChangeForm", "Iznos:"))
        self.buttonSolve.setText(_translate("CoinChangeForm", "Pronadji kombinacije"))
        self.labelStatus.setText(_translate("CoinChangeForm", "Broj resenja: 0"))
