# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.1/palindrome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PalindromeChecker(object):
    def setupUi(self, PalindromeChecker):
        PalindromeChecker.setObjectName("PalindromeChecker")
        PalindromeChecker.resize(300, 150)
        self.centralwidget = QtWidgets.QWidget(PalindromeChecker)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_word = QtWidgets.QLineEdit(self.centralwidget)
        self.le_word.setObjectName("le_word")
        self.verticalLayout.addWidget(self.le_word)
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check.setObjectName("btn_check")
        self.verticalLayout.addWidget(self.btn_check)
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.verticalLayout.addWidget(self.lbl_result)
        PalindromeChecker.setCentralWidget(self.centralwidget)

        self.retranslateUi(PalindromeChecker)
        QtCore.QMetaObject.connectSlotsByName(PalindromeChecker)

    def retranslateUi(self, PalindromeChecker):
        _translate = QtCore.QCoreApplication.translate
        PalindromeChecker.setWindowTitle(_translate("PalindromeChecker", "Provera palindroma"))
        self.le_word.setPlaceholderText(_translate("PalindromeChecker", "Unesi reč"))
        self.btn_check.setText(_translate("PalindromeChecker", "Proveri"))
