# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.7/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(50, 20, 300, 30))
        self.label_title.setObjectName("label_title")
        self.radio_A = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_A.setGeometry(QtCore.QRect(50, 70, 150, 20))
        self.radio_A.setObjectName("radio_A")
        self.radio_B = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_B.setGeometry(QtCore.QRect(50, 100, 150, 20))
        self.radio_B.setObjectName("radio_B")
        self.radio_C = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_C.setGeometry(QtCore.QRect(50, 130, 150, 20))
        self.radio_C.setObjectName("radio_C")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(50, 180, 300, 30))
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Radio Button Example"))
        self.label_title.setText(_translate("MainWindow", "Select one option:"))
        self.radio_A.setText(_translate("MainWindow", "Option A"))
        self.radio_B.setText(_translate("MainWindow", "Option B"))
        self.radio_C.setText(_translate("MainWindow", "Option C"))
        self.label_result.setText(_translate("MainWindow", "No selection"))
