# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.9/file_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileExplorer(object):
    def setupUi(self, FileExplorer):
        FileExplorer.setObjectName("FileExplorer")
        FileExplorer.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileExplorer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.linePath = QtWidgets.QLineEdit(FileExplorer)
        self.linePath.setObjectName("linePath")
        self.pathLayout.addWidget(self.linePath)
        self.btnBrowse = QtWidgets.QPushButton(FileExplorer)
        self.btnBrowse.setObjectName("btnBrowse")
        self.pathLayout.addWidget(self.btnBrowse)
        self.verticalLayout.addLayout(self.pathLayout)
        self.treeFiles = QtWidgets.QTreeWidget(FileExplorer)
        self.treeFiles.setColumnCount(3)
        self.treeFiles.setObjectName("treeFiles")
        self.verticalLayout.addWidget(self.treeFiles)

        self.retranslateUi(FileExplorer)
        QtCore.QMetaObject.connectSlotsByName(FileExplorer)

    def retranslateUi(self, FileExplorer):
        _translate = QtCore.QCoreApplication.translate
        FileExplorer.setWindowTitle(_translate("FileExplorer", "PyQt5 File Explorer"))
        self.btnBrowse.setText(_translate("FileExplorer", "Browse"))
        self.treeFiles.headerItem().setText(0, _translate("FileExplorer", "Name"))
        self.treeFiles.headerItem().setText(1, _translate("FileExplorer", "Type"))
        self.treeFiles.headerItem().setText(2, _translate("FileExplorer", "Size"))
