# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_12/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KnapsackForm(object):
    def setupUi(self, KnapsackForm):
        KnapsackForm.setObjectName("KnapsackForm")
        KnapsackForm.resize(560, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(KnapsackForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(KnapsackForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.labelCapacity = QtWidgets.QLabel(KnapsackForm)
        self.labelCapacity.setObjectName("labelCapacity")
        self.topLayout.addWidget(self.labelCapacity)
        self.spinCapacity = QtWidgets.QSpinBox(KnapsackForm)
        self.spinCapacity.setMinimum(0)
        self.spinCapacity.setMaximum(200)
        self.spinCapacity.setProperty("value", 9)
        self.spinCapacity.setObjectName("spinCapacity")
        self.topLayout.addWidget(self.spinCapacity)
        self.buttonDefaults = QtWidgets.QPushButton(KnapsackForm)
        self.buttonDefaults.setObjectName("buttonDefaults")
        self.topLayout.addWidget(self.buttonDefaults)
        self.buttonSolve = QtWidgets.QPushButton(KnapsackForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.topLayout.addWidget(self.buttonSolve)
        self.verticalLayout.addLayout(self.topLayout)
        self.tableItems = QtWidgets.QTableWidget(KnapsackForm)
        self.tableItems.setObjectName("tableItems")
        self.tableItems.setColumnCount(0)
        self.tableItems.setRowCount(0)
        self.verticalLayout.addWidget(self.tableItems)
        self.labelStatus = QtWidgets.QLabel(KnapsackForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(KnapsackForm)
        QtCore.QMetaObject.connectSlotsByName(KnapsackForm)

    def retranslateUi(self, KnapsackForm):
        _translate = QtCore.QCoreApplication.translate
        KnapsackForm.setWindowTitle(_translate("KnapsackForm", "Optimizator ranca"))
        self.labelTitle.setText(_translate("KnapsackForm", "Optimizator ranca"))
        self.labelCapacity.setText(_translate("KnapsackForm", "Kapacitet:"))
        self.buttonDefaults.setText(_translate("KnapsackForm", "Ucitaj primer"))
        self.buttonSolve.setText(_translate("KnapsackForm", "Maksimizuj"))
        self.labelStatus.setText(_translate("KnapsackForm", "Spremno."))
