# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.4/click_counter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClickCounter(object):
    def setupUi(self, ClickCounter):
        ClickCounter.setObjectName("ClickCounter")
        ClickCounter.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClickCounter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCount = QtWidgets.QLabel(ClickCounter)
        self.labelCount.setObjectName("labelCount")
        self.verticalLayout.addWidget(self.labelCount)
        self.buttonClick = QtWidgets.QPushButton(ClickCounter)
        self.buttonClick.setObjectName("buttonClick")
        self.verticalLayout.addWidget(self.buttonClick)
        self.labelMessage = QtWidgets.QLabel(ClickCounter)
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout.addWidget(self.labelMessage)

        self.retranslateUi(ClickCounter)
        QtCore.QMetaObject.connectSlotsByName(ClickCounter)

    def retranslateUi(self, ClickCounter):
        _translate = QtCore.QCoreApplication.translate
        ClickCounter.setWindowTitle(_translate("ClickCounter", "Click Counter"))
        self.labelCount.setText(_translate("ClickCounter", "Klikovi: 0"))
        self.labelCount.setStyleSheet(_translate("ClickCounter", "font-size: 18px;"))
        self.buttonClick.setText(_translate("ClickCounter", "Klikni me"))
        self.buttonClick.setStyleSheet(_translate("ClickCounter", "font-size: 16px; padding: 10px;"))
        self.labelMessage.setStyleSheet(_translate("ClickCounter", "color: red; font-size: 16px;"))
