# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.5/password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerator(object):
    def setupUi(self, PasswordGenerator):
        PasswordGenerator.setObjectName("PasswordGenerator")
        self.vboxlayout = QtWidgets.QVBoxLayout(PasswordGenerator)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(PasswordGenerator)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.lengthSpinBox = QtWidgets.QSpinBox(PasswordGenerator)
        self.lengthSpinBox.setMinimum(4)
        self.lengthSpinBox.setMaximum(64)
        self.lengthSpinBox.setProperty("value", 12)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.vboxlayout.addWidget(self.lengthSpinBox)
        self.lowerCheckBox = QtWidgets.QCheckBox(PasswordGenerator)
        self.lowerCheckBox.setChecked(True)
        self.lowerCheckBox.setObjectName("lowerCheckBox")
        self.vboxlayout.addWidget(self.lowerCheckBox)
        self.upperCheckBox = QtWidgets.QCheckBox(PasswordGenerator)
        self.upperCheckBox.setChecked(True)
        self.upperCheckBox.setObjectName("upperCheckBox")
        self.vboxlayout.addWidget(self.upperCheckBox)
        self.digitsCheckBox = QtWidgets.QCheckBox(PasswordGenerator)
        self.digitsCheckBox.setChecked(True)
        self.digitsCheckBox.setObjectName("digitsCheckBox")
        self.vboxlayout.addWidget(self.digitsCheckBox)
        self.symbolsCheckBox = QtWidgets.QCheckBox(PasswordGenerator)
        self.symbolsCheckBox.setObjectName("symbolsCheckBox")
        self.vboxlayout.addWidget(self.symbolsCheckBox)
        self.generateButton = QtWidgets.QPushButton(PasswordGenerator)
        self.generateButton.setObjectName("generateButton")
        self.vboxlayout.addWidget(self.generateButton)
        self.passwordLineEdit = QtWidgets.QLineEdit(PasswordGenerator)
        self.passwordLineEdit.setReadOnly(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.vboxlayout.addWidget(self.passwordLineEdit)

        self.retranslateUi(PasswordGenerator)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerator)

    def retranslateUi(self, PasswordGenerator):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerator.setWindowTitle(_translate("PasswordGenerator", "Password Generator"))
        self.label.setText(_translate("PasswordGenerator", "Password Length"))
        self.lowerCheckBox.setText(_translate("PasswordGenerator", "Include lowercase (a-z)"))
        self.upperCheckBox.setText(_translate("PasswordGenerator", "Include uppercase (A-Z)"))
        self.digitsCheckBox.setText(_translate("PasswordGenerator", "Include digits (0-9)"))
        self.symbolsCheckBox.setText(_translate("PasswordGenerator", "Include symbols (!@#$)"))
        self.generateButton.setText(_translate("PasswordGenerator", "Generate Password"))
