solve(Vars) :-
    Vars = [A,B,C,D,E,F,G,H],
    Vars :: 1..8,
    alldifferent(Vars),
    A #\= B+1, A #\= B-1,
    A #\= C+2, A #\= C-2,
    A #\= D+3, A #\= D-3,
    A #\= E+4, A #\= E-4,
    A #\= F+5, A #\= F-5,
    A #\= G+6, A #\= G-6,
    A #\= H+7, A #\= H-7,
    B #\= C+1, B #\= C-1,
    B #\= D+2, B #\= D-2,
    B #\= E+3, B #\= E-3,
    B #\= F+4, B #\= F-4,
    B #\= G+5, B #\= G-5,
    B #\= H+6, B #\= H-6,
    C #\= D+1, C #\= D-1,
    C #\= E+2, C #\= E-2,
    C #\= F+3, C #\= F-3,
    C #\= G+4, C #\= G-4,
    C #\= H+5, C #\= H-5,
    D #\= E+1, D #\= E-1,
    D #\= F+2, D #\= F-2,
    D #\= G+3, D #\= G-3,
    D #\= H+4, D #\= H-4,
    E #\= F+1, E #\= F-1,
    E #\= G+2, E #\= G-2,
    E #\= H+3, E #\= H-3,
    F #\= G+1, F #\= G-1,
    F #\= H+2, F #\= H-2,
    G #\= H+1, G #\= H-1,
    labeling(Vars),
    writeln(Vars),
    fail.
solve(_).
