# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.2/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 150)
        self.vboxlayout = QtWidgets.QVBoxLayout(Form)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setObjectName("button")
        self.vboxlayout.addWidget(self.button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Form", "Hello OOP!"))
        self.button.setText(_translate("Form", "Click me"))
