# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_15/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapColoringForm(object):
    def setupUi(self, MapColoringForm):
        MapColoringForm.setObjectName("MapColoringForm")
        MapColoringForm.resize(560, 330)
        self.verticalLayout = QtWidgets.QVBoxLayout(MapColoringForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(MapColoringForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.labelColors = QtWidgets.QLabel(MapColoringForm)
        self.labelColors.setObjectName("labelColors")
        self.controlLayout.addWidget(self.labelColors)
        self.spinColors = QtWidgets.QSpinBox(MapColoringForm)
        self.spinColors.setMinimum(4)
        self.spinColors.setMaximum(5)
        self.spinColors.setProperty("value", 3)
        self.spinColors.setObjectName("spinColors")
        self.controlLayout.addWidget(self.spinColors)
        self.buttonSolve = QtWidgets.QPushButton(MapColoringForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.controlLayout.addWidget(self.buttonSolve)
        self.verticalLayout.addLayout(self.controlLayout)
        self.tableSolutions = QtWidgets.QTableWidget(MapColoringForm)
        self.tableSolutions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSolutions.setObjectName("tableSolutions")
        self.tableSolutions.setColumnCount(0)
        self.tableSolutions.setRowCount(0)
        self.verticalLayout.addWidget(self.tableSolutions)
        self.labelStatus = QtWidgets.QLabel(MapColoringForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(MapColoringForm)
        QtCore.QMetaObject.connectSlotsByName(MapColoringForm)

    def retranslateUi(self, MapColoringForm):
        _translate = QtCore.QCoreApplication.translate
        MapColoringForm.setWindowTitle(_translate("MapColoringForm", "Bojenje mape"))
        self.labelTitle.setText(_translate("MapColoringForm", "Bojenje mape ogranicenjima"))
        self.labelColors.setText(_translate("MapColoringForm", "Broj boja:"))
        self.buttonSolve.setText(_translate("MapColoringForm", "Oboji"))
        self.labelStatus.setText(_translate("MapColoringForm", "Broj bojenja: 0"))
