# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.15/quick_reflex.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuickReflexGame(object):
    def setupUi(self, QuickReflexGame):
        QuickReflexGame.setObjectName("QuickReflexGame")
        QuickReflexGame.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(QuickReflexGame)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_click = QtWidgets.QPushButton(self.centralwidget)
        self.btn_click.setGeometry(QtCore.QRect(150, 120, 100, 40))
        self.btn_click.setObjectName("btn_click")
        self.lbl_time = QtWidgets.QLabel(self.centralwidget)
        self.lbl_time.setGeometry(QtCore.QRect(10, 10, 100, 30))
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_score = QtWidgets.QLabel(self.centralwidget)
        self.lbl_score.setGeometry(QtCore.QRect(150, 10, 120, 30))
        self.lbl_score.setObjectName("lbl_score")
        QuickReflexGame.setCentralWidget(self.centralwidget)

        self.retranslateUi(QuickReflexGame)
        QtCore.QMetaObject.connectSlotsByName(QuickReflexGame)

    def retranslateUi(self, QuickReflexGame):
        _translate = QtCore.QCoreApplication.translate
        QuickReflexGame.setWindowTitle(_translate("QuickReflexGame", "Brzi refleksi"))
        self.btn_click.setText(_translate("QuickReflexGame", "Klikni me"))
        self.lbl_time.setText(_translate("QuickReflexGame", "Vreme: 10"))
        self.lbl_score.setText(_translate("QuickReflexGame", "Rezultat: 0"))
