# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.3/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNext = QtWidgets.QPushButton(Form)
        self.btnNext.setObjectName("btnNext")
        self.verticalLayout.addWidget(self.btnNext)
        self.textOutput = QtWidgets.QTextEdit(Form)
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.verticalLayout.addWidget(self.textOutput)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Fibonacci Generator"))
        self.btnNext.setText(_translate("Form", "Next Fibonacci"))
