# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.17/music_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(400, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(MusicPlayer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnPlay = QtWidgets.QPushButton(MusicPlayer)
        self.btnPlay.setMinimumSize(QtCore.QSize(50, 50))
        self.btnPlay.setObjectName("btnPlay")
        self.buttonLayout.addWidget(self.btnPlay)
        self.btnPause = QtWidgets.QPushButton(MusicPlayer)
        self.btnPause.setMinimumSize(QtCore.QSize(50, 50))
        self.btnPause.setObjectName("btnPause")
        self.buttonLayout.addWidget(self.btnPause)
        self.btnStop = QtWidgets.QPushButton(MusicPlayer)
        self.btnStop.setMinimumSize(QtCore.QSize(50, 50))
        self.btnStop.setObjectName("btnStop")
        self.buttonLayout.addWidget(self.btnStop)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.btnLoad = QtWidgets.QPushButton(MusicPlayer)
        self.btnLoad.setObjectName("btnLoad")
        self.verticalLayout.addWidget(self.btnLoad)
        self.slider = QtWidgets.QSlider(MusicPlayer)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.verticalLayout.addWidget(self.slider)
        self.label = QtWidgets.QLabel(MusicPlayer)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(MusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "PyQt5 Music Player"))
        self.btnLoad.setText(_translate("MusicPlayer", "Load Music"))
        self.label.setText(_translate("MusicPlayer", "No file loaded"))
