# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.6/char_counter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CharCounter(object):
    def setupUi(self, CharCounter):
        CharCounter.setObjectName("CharCounter")
        CharCounter.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(CharCounter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.te_input = QtWidgets.QTextEdit(self.centralwidget)
        self.te_input.setObjectName("te_input")
        self.verticalLayout.addWidget(self.te_input)
        self.lbl_chars = QtWidgets.QLabel(self.centralwidget)
        self.lbl_chars.setObjectName("lbl_chars")
        self.verticalLayout.addWidget(self.lbl_chars)
        self.lbl_words = QtWidgets.QLabel(self.centralwidget)
        self.lbl_words.setObjectName("lbl_words")
        self.verticalLayout.addWidget(self.lbl_words)
        CharCounter.setCentralWidget(self.centralwidget)

        self.retranslateUi(CharCounter)
        QtCore.QMetaObject.connectSlotsByName(CharCounter)

    def retranslateUi(self, CharCounter):
        _translate = QtCore.QCoreApplication.translate
        CharCounter.setWindowTitle(_translate("CharCounter", "Brojač karaktera"))
        self.lbl_chars.setText(_translate("CharCounter", "Karakteri: 0"))
        self.lbl_words.setText(_translate("CharCounter", "Reči: 0"))
