# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.7/guess_number.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuessNumber(object):
    def setupUi(self, GuessNumber):
        GuessNumber.setObjectName("GuessNumber")
        GuessNumber.resize(350, 220)
        self.verticalLayout = QtWidgets.QVBoxLayout(GuessNumber)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelInfo = QtWidgets.QLabel(GuessNumber)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.lineEditNumber = QtWidgets.QLineEdit(GuessNumber)
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.verticalLayout.addWidget(self.lineEditNumber)
        self.buttonGuess = QtWidgets.QPushButton(GuessNumber)
        self.buttonGuess.setObjectName("buttonGuess")
        self.verticalLayout.addWidget(self.buttonGuess)
        self.labelResult = QtWidgets.QLabel(GuessNumber)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)
        self.labelAttempts = QtWidgets.QLabel(GuessNumber)
        self.labelAttempts.setObjectName("labelAttempts")
        self.verticalLayout.addWidget(self.labelAttempts)

        self.retranslateUi(GuessNumber)
        QtCore.QMetaObject.connectSlotsByName(GuessNumber)

    def retranslateUi(self, GuessNumber):
        _translate = QtCore.QCoreApplication.translate
        GuessNumber.setWindowTitle(_translate("GuessNumber", "Pogađanje broja"))
        self.labelInfo.setText(_translate("GuessNumber", "Pogodi broj od 1 do 100"))
        self.lineEditNumber.setPlaceholderText(_translate("GuessNumber", "Unesi broj"))
        self.buttonGuess.setText(_translate("GuessNumber", "Pogodi"))
        self.labelResult.setStyleSheet(_translate("GuessNumber", "font-size: 16px;"))
        self.labelAttempts.setText(_translate("GuessNumber", "Pokušaji: 0 / 10"))
