# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_14/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MagicSquareForm(object):
    def setupUi(self, MagicSquareForm):
        MagicSquareForm.setObjectName("MagicSquareForm")
        MagicSquareForm.resize(320, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(MagicSquareForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(MagicSquareForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.tableSquare = QtWidgets.QTableWidget(MagicSquareForm)
        self.tableSquare.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSquare.setObjectName("tableSquare")
        self.tableSquare.setColumnCount(0)
        self.tableSquare.setRowCount(0)
        self.verticalLayout.addWidget(self.tableSquare)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonSolve = QtWidgets.QPushButton(MagicSquareForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.buttonLayout.addWidget(self.buttonSolve)
        self.buttonPrevious = QtWidgets.QPushButton(MagicSquareForm)
        self.buttonPrevious.setObjectName("buttonPrevious")
        self.buttonLayout.addWidget(self.buttonPrevious)
        self.buttonNext = QtWidgets.QPushButton(MagicSquareForm)
        self.buttonNext.setObjectName("buttonNext")
        self.buttonLayout.addWidget(self.buttonNext)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.labelStatus = QtWidgets.QLabel(MagicSquareForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(MagicSquareForm)
        QtCore.QMetaObject.connectSlotsByName(MagicSquareForm)

    def retranslateUi(self, MagicSquareForm):
        _translate = QtCore.QCoreApplication.translate
        MagicSquareForm.setWindowTitle(_translate("MagicSquareForm", "Magicni kvadrat"))
        self.labelTitle.setText(_translate("MagicSquareForm", "Magicni kvadrat 3x3"))
        self.buttonSolve.setText(_translate("MagicSquareForm", "Pronadji"))
        self.buttonPrevious.setText(_translate("MagicSquareForm", "Prethodno"))
        self.buttonNext.setText(_translate("MagicSquareForm", "Sledece"))
        self.labelStatus.setText(_translate("MagicSquareForm", "Resenje 0/0"))
