# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_10/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueensForm(object):
    def setupUi(self, QueensForm):
        QueensForm.setObjectName("QueensForm")
        QueensForm.resize(420, 430)
        self.verticalLayout = QtWidgets.QVBoxLayout(QueensForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(QueensForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.labelSize = QtWidgets.QLabel(QueensForm)
        self.labelSize.setObjectName("labelSize")
        self.controlLayout.addWidget(self.labelSize)
        self.spinSize = QtWidgets.QSpinBox(QueensForm)
        self.spinSize.setMinimum(4)
        self.spinSize.setMaximum(10)
        self.spinSize.setProperty("value", 8)
        self.spinSize.setObjectName("spinSize")
        self.controlLayout.addWidget(self.spinSize)
        self.buttonSolve = QtWidgets.QPushButton(QueensForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.controlLayout.addWidget(self.buttonSolve)
        self.buttonPrevious = QtWidgets.QPushButton(QueensForm)
        self.buttonPrevious.setObjectName("buttonPrevious")
        self.controlLayout.addWidget(self.buttonPrevious)
        self.buttonNext = QtWidgets.QPushButton(QueensForm)
        self.buttonNext.setObjectName("buttonNext")
        self.controlLayout.addWidget(self.buttonNext)
        self.verticalLayout.addLayout(self.controlLayout)
        self.tableBoard = QtWidgets.QTableWidget(QueensForm)
        self.tableBoard.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableBoard.setShowGrid(True)
        self.tableBoard.setObjectName("tableBoard")
        self.tableBoard.setColumnCount(0)
        self.tableBoard.setRowCount(0)
        self.verticalLayout.addWidget(self.tableBoard)
        self.labelStatus = QtWidgets.QLabel(QueensForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(QueensForm)
        QtCore.QMetaObject.connectSlotsByName(QueensForm)

    def retranslateUi(self, QueensForm):
        _translate = QtCore.QCoreApplication.translate
        QueensForm.setWindowTitle(_translate("QueensForm", "N dama"))
        self.labelTitle.setText(_translate("QueensForm", "Vizuelizacija problema N dama"))
        self.labelSize.setText(_translate("QueensForm", "Dimenzija:"))
        self.buttonSolve.setText(_translate("QueensForm", "Resi"))
        self.buttonPrevious.setText(_translate("QueensForm", "Prethodno"))
        self.buttonNext.setText(_translate("QueensForm", "Sledece"))
        self.labelStatus.setText(_translate("QueensForm", "Resenje 0/0"))
