# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.2/timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimerApp(object):
    def setupUi(self, TimerApp):
        TimerApp.setObjectName("TimerApp")
        TimerApp.resize(300, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimerApp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTime = QtWidgets.QLabel(TimerApp)
        self.labelTime.setObjectName("labelTime")
        self.verticalLayout.addWidget(self.labelTime)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonStart = QtWidgets.QPushButton(TimerApp)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(TimerApp)
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout.addWidget(self.buttonStop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TimerApp)
        QtCore.QMetaObject.connectSlotsByName(TimerApp)

    def retranslateUi(self, TimerApp):
        _translate = QtCore.QCoreApplication.translate
        TimerApp.setWindowTitle(_translate("TimerApp", "Štoperica"))
        self.labelTime.setText(_translate("TimerApp", "0 s"))
        self.labelTime.setStyleSheet(_translate("TimerApp", "font-size: 24px;"))
        self.buttonStart.setText(_translate("TimerApp", "Start"))
        self.buttonStop.setText(_translate("TimerApp", "Stop"))
