# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.1.9/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridWindow(object):
    def setupUi(self, GridWindow):
        GridWindow.setObjectName("GridWindow")
        GridWindow.resize(300, 200)
        self.gridLayout = QtWidgets.QGridLayout(GridWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.button1 = QtWidgets.QPushButton(GridWindow)
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 0, 0, 1, 1)
        self.button2 = QtWidgets.QPushButton(GridWindow)
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 0, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(GridWindow)
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 1, 0, 1, 1)
        self.button4 = QtWidgets.QPushButton(GridWindow)
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 1, 1, 1, 1)
        self.button5 = QtWidgets.QPushButton(GridWindow)
        self.button5.setObjectName("button5")
        self.gridLayout.addWidget(self.button5, 2, 0, 1, 2)

        self.retranslateUi(GridWindow)
        QtCore.QMetaObject.connectSlotsByName(GridWindow)

    def retranslateUi(self, GridWindow):
        _translate = QtCore.QCoreApplication.translate
        GridWindow.setWindowTitle(_translate("GridWindow", "PyQt5 Grid Layout Example"))
        self.button1.setText(_translate("GridWindow", "Button 1"))
        self.button2.setText(_translate("GridWindow", "Button 2"))
        self.button3.setText(_translate("GridWindow", "Button 3"))
        self.button4.setText(_translate("GridWindow", "Button 4"))
        self.button5.setText(_translate("GridWindow", "Button 5"))
