# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_08/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MagicSequenceForm(object):
    def setupUi(self, MagicSequenceForm):
        MagicSequenceForm.setObjectName("MagicSequenceForm")
        MagicSequenceForm.resize(420, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(MagicSequenceForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(MagicSequenceForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.labelLength = QtWidgets.QLabel(MagicSequenceForm)
        self.labelLength.setObjectName("labelLength")
        self.inputLayout.addWidget(self.labelLength)
        self.spinLength = QtWidgets.QSpinBox(MagicSequenceForm)
        self.spinLength.setMinimum(1)
        self.spinLength.setMaximum(8)
        self.spinLength.setProperty("value", 5)
        self.spinLength.setObjectName("spinLength")
        self.inputLayout.addWidget(self.spinLength)
        self.buttonSolve = QtWidgets.QPushButton(MagicSequenceForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.inputLayout.addWidget(self.buttonSolve)
        self.verticalLayout.addLayout(self.inputLayout)
        self.listSolutions = QtWidgets.QListWidget(MagicSequenceForm)
        self.listSolutions.setObjectName("listSolutions")
        self.verticalLayout.addWidget(self.listSolutions)
        self.labelStatus = QtWidgets.QLabel(MagicSequenceForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(MagicSequenceForm)
        QtCore.QMetaObject.connectSlotsByName(MagicSequenceForm)

    def retranslateUi(self, MagicSequenceForm):
        _translate = QtCore.QCoreApplication.translate
        MagicSequenceForm.setWindowTitle(_translate("MagicSequenceForm", "Magicna sekvenca"))
        self.labelTitle.setText(_translate("MagicSequenceForm", "Generator magicnih sekvenci"))
        self.labelLength.setText(_translate("MagicSequenceForm", "Duzina:"))
        self.buttonSolve.setText(_translate("MagicSequenceForm", "Pronadji"))
        self.labelStatus.setText(_translate("MagicSequenceForm", "Broj resenja: 0"))
