# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.12/todo_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToDoList(object):
    def setupUi(self, ToDoList):
        ToDoList.setObjectName("ToDoList")
        ToDoList.resize(200, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ToDoList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.lineTask = QtWidgets.QLineEdit(ToDoList)
        self.lineTask.setObjectName("lineTask")
        self.inputLayout.addWidget(self.lineTask)
        self.btnAdd = QtWidgets.QPushButton(ToDoList)
        self.btnAdd.setObjectName("btnAdd")
        self.inputLayout.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.inputLayout)
        self.listTasks = QtWidgets.QListWidget(ToDoList)
        self.listTasks.setObjectName("listTasks")
        self.verticalLayout.addWidget(self.listTasks)
        self.btnDelete = QtWidgets.QPushButton(ToDoList)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)

        self.retranslateUi(ToDoList)
        QtCore.QMetaObject.connectSlotsByName(ToDoList)

    def retranslateUi(self, ToDoList):
        _translate = QtCore.QCoreApplication.translate
        ToDoList.setWindowTitle(_translate("ToDoList", "PyQt5 To-Do List"))
        self.btnAdd.setText(_translate("ToDoList", "Add"))
        self.btnDelete.setText(_translate("ToDoList", "Delete Selected"))
