# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_13/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainingPlannerForm(object):
    def setupUi(self, TrainingPlannerForm):
        TrainingPlannerForm.setObjectName("TrainingPlannerForm")
        TrainingPlannerForm.resize(560, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(TrainingPlannerForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(TrainingPlannerForm)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelBudget = QtWidgets.QLabel(TrainingPlannerForm)
        self.labelBudget.setObjectName("labelBudget")
        self.gridLayout.addWidget(self.labelBudget, 0, 0, 1, 1)
        self.spinBudget = QtWidgets.QSpinBox(TrainingPlannerForm)
        self.spinBudget.setMaximum(1000000)
        self.spinBudget.setProperty("value", 26000)
        self.spinBudget.setObjectName("spinBudget")
        self.gridLayout.addWidget(self.spinBudget, 0, 1, 1, 1)
        self.labelHours = QtWidgets.QLabel(TrainingPlannerForm)
        self.labelHours.setObjectName("labelHours")
        self.gridLayout.addWidget(self.labelHours, 0, 2, 1, 1)
        self.spinHours = QtWidgets.QSpinBox(TrainingPlannerForm)
        self.spinHours.setMaximum(1000000)
        self.spinHours.setProperty("value", 51200)
        self.spinHours.setObjectName("spinHours")
        self.gridLayout.addWidget(self.spinHours, 0, 3, 1, 1)
        self.labelWorkers = QtWidgets.QLabel(TrainingPlannerForm)
        self.labelWorkers.setObjectName("labelWorkers")
        self.gridLayout.addWidget(self.labelWorkers, 1, 0, 1, 1)
        self.spinWorkers = QtWidgets.QSpinBox(TrainingPlannerForm)
        self.spinWorkers.setMaximum(10000)
        self.spinWorkers.setProperty("value", 250)
        self.spinWorkers.setObjectName("spinWorkers")
        self.gridLayout.addWidget(self.spinWorkers, 1, 1, 1, 1)
        self.buttonSolve = QtWidgets.QPushButton(TrainingPlannerForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.gridLayout.addWidget(self.buttonSolve, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tableCourses = QtWidgets.QTableWidget(TrainingPlannerForm)
        self.tableCourses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCourses.setObjectName("tableCourses")
        self.tableCourses.setColumnCount(0)
        self.tableCourses.setRowCount(0)
        self.verticalLayout.addWidget(self.tableCourses)
        self.labelStatus = QtWidgets.QLabel(TrainingPlannerForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(TrainingPlannerForm)
        QtCore.QMetaObject.connectSlotsByName(TrainingPlannerForm)

    def retranslateUi(self, TrainingPlannerForm):
        _translate = QtCore.QCoreApplication.translate
        TrainingPlannerForm.setWindowTitle(_translate("TrainingPlannerForm", "Plan obuka"))
        self.labelTitle.setText(_translate("TrainingPlannerForm", "Plan obuka zaposlenih"))
        self.labelBudget.setText(_translate("TrainingPlannerForm", "Budzet:"))
        self.labelHours.setText(_translate("TrainingPlannerForm", "Projektni sati:"))
        self.labelWorkers.setText(_translate("TrainingPlannerForm", "Broj radnika:"))
        self.buttonSolve.setText(_translate("TrainingPlannerForm", "Izracunaj plan"))
        self.labelStatus.setText(_translate("TrainingPlannerForm", "Spremno."))
