# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_03/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormatterWindow(object):
    def setupUi(self, FormatterWindow):
        FormatterWindow.setObjectName("FormatterWindow")
        FormatterWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(FormatterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.boldButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.boldButton.setFont(font)
        self.boldButton.setObjectName("boldButton")
        self.toolbarLayout.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.italicButton.setFont(font)
        self.italicButton.setObjectName("italicButton")
        self.toolbarLayout.addWidget(self.italicButton)
        self.underlineButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.underlineButton.setFont(font)
        self.underlineButton.setObjectName("underlineButton")
        self.toolbarLayout.addWidget(self.underlineButton)
        self.fontCombo = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontCombo.setObjectName("fontCombo")
        self.toolbarLayout.addWidget(self.fontCombo)
        self.fontSizeSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.fontSizeSpin.setMinimum(6)
        self.fontSizeSpin.setMaximum(72)
        self.fontSizeSpin.setProperty("value", 12)
        self.fontSizeSpin.setObjectName("fontSizeSpin")
        self.toolbarLayout.addWidget(self.fontSizeSpin)
        self.verticalLayout.addLayout(self.toolbarLayout)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        FormatterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormatterWindow)
        QtCore.QMetaObject.connectSlotsByName(FormatterWindow)

    def retranslateUi(self, FormatterWindow):
        _translate = QtCore.QCoreApplication.translate
        FormatterWindow.setWindowTitle(_translate("FormatterWindow", "Text Formatter"))
        self.boldButton.setText(_translate("FormatterWindow", "B"))
        self.italicButton.setText(_translate("FormatterWindow", "I"))
        self.underlineButton.setText(_translate("FormatterWindow", "U"))
