# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.18/file_preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilePreview(object):
    def setupUi(self, FilePreview):
        FilePreview.setObjectName("FilePreview")
        FilePreview.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(FilePreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLoad = QtWidgets.QPushButton(FilePreview)
        self.btnLoad.setObjectName("btnLoad")
        self.verticalLayout.addWidget(self.btnLoad)
        self.labelFileName = QtWidgets.QLabel(FilePreview)
        self.labelFileName.setObjectName("labelFileName")
        self.verticalLayout.addWidget(self.labelFileName)
        self.scrollArea = QtWidgets.QScrollArea(FilePreview)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setObjectName("scrollLayout")
        self.textPreview = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textPreview.setReadOnly(True)
        self.textPreview.setObjectName("textPreview")
        self.scrollLayout.addWidget(self.textPreview)
        self.imagePreview = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imagePreview.setObjectName("imagePreview")
        self.scrollLayout.addWidget(self.imagePreview)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(FilePreview)
        QtCore.QMetaObject.connectSlotsByName(FilePreview)

    def retranslateUi(self, FilePreview):
        _translate = QtCore.QCoreApplication.translate
        FilePreview.setWindowTitle(_translate("FilePreview", "File Preview App"))
        self.btnLoad.setText(_translate("FilePreview", "Load File"))
        self.labelFileName.setText(_translate("FilePreview", "No file loaded"))
