# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/2.2.16/hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HangmanGame(object):
    def setupUi(self, HangmanGame):
        HangmanGame.setObjectName("HangmanGame")
        HangmanGame.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(HangmanGame)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_word = QtWidgets.QLabel(self.centralwidget)
        self.lbl_word.setMinimumSize(QtCore.QSize(0, 40))
        self.lbl_word.setObjectName("lbl_word")
        self.verticalLayout.addWidget(self.lbl_word)
        self.lbl_errors = QtWidgets.QLabel(self.centralwidget)
        self.lbl_errors.setObjectName("lbl_errors")
        self.verticalLayout.addWidget(self.lbl_errors)
        self.le_letter = QtWidgets.QLineEdit(self.centralwidget)
        self.le_letter.setObjectName("le_letter")
        self.verticalLayout.addWidget(self.le_letter)
        self.btn_guess = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guess.setObjectName("btn_guess")
        self.verticalLayout.addWidget(self.btn_guess)
        HangmanGame.setCentralWidget(self.centralwidget)

        self.retranslateUi(HangmanGame)
        QtCore.QMetaObject.connectSlotsByName(HangmanGame)

    def retranslateUi(self, HangmanGame):
        _translate = QtCore.QCoreApplication.translate
        HangmanGame.setWindowTitle(_translate("HangmanGame", "Vešala"))
        self.lbl_word.setText(_translate("HangmanGame", "_ _ _ _ _"))
        self.lbl_errors.setText(_translate("HangmanGame", "Greške: 0"))
        self.le_letter.setPlaceholderText(_translate("HangmanGame", "Unesi slovo"))
        self.btn_guess.setText(_translate("HangmanGame", "Pogodi"))
