# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp-materials/component/PENDING_EDITS/E_09_1/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryptarithmForm(object):
    def setupUi(self, CryptarithmForm):
        CryptarithmForm.setObjectName("CryptarithmForm")
        CryptarithmForm.resize(580, 310)
        self.verticalLayout = QtWidgets.QVBoxLayout(CryptarithmForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(CryptarithmForm)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.buttonSolve = QtWidgets.QPushButton(CryptarithmForm)
        self.buttonSolve.setObjectName("buttonSolve")
        self.verticalLayout.addWidget(self.buttonSolve)
        self.tableSolutions = QtWidgets.QTableWidget(CryptarithmForm)
        self.tableSolutions.setObjectName("tableSolutions")
        self.tableSolutions.setColumnCount(0)
        self.tableSolutions.setRowCount(0)
        self.verticalLayout.addWidget(self.tableSolutions)
        self.labelStatus = QtWidgets.QLabel(CryptarithmForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(CryptarithmForm)
        QtCore.QMetaObject.connectSlotsByName(CryptarithmForm)

    def retranslateUi(self, CryptarithmForm):
        _translate = QtCore.QCoreApplication.translate
        CryptarithmForm.setWindowTitle(_translate("CryptarithmForm", "MEN * AND = WOMEN"))
        self.labelTitle.setText(_translate("CryptarithmForm", "Kriptoaritmetika: MEN * AND = WOMEN"))
        self.buttonSolve.setText(_translate("CryptarithmForm", "Pronadji sva resenja"))
        self.labelStatus.setText(_translate("CryptarithmForm", "Broj resenja: 0"))
